//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessibleEPUB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_MessageBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_MessageBox() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessibleEPUB.Resource_MessageBox", typeof(Resource_MessageBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will only be shown when the program is restarted.
        /// </summary>
        internal static string changesContent {
            get {
                return ResourceManager.GetString("changesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        internal static string changesTitle {
            get {
                return ResourceManager.GetString("changesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem converting from WYSIWYG to HTML.
        /// </summary>
        internal static string conversionContent {
            get {
                return ResourceManager.GetString("conversionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion problem.
        /// </summary>
        internal static string conversionTitle {
            get {
                return ResourceManager.GetString("conversionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is already in JavaScript format.
        /// </summary>
        internal static string cssToJsContent {
            get {
                return ResourceManager.GetString("cssToJsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already JavaScript format.
        /// </summary>
        internal static string cssToJsTitle {
            get {
                return ResourceManager.GetString("cssToJsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alternative text is empty..
        /// </summary>
        internal static string emptyAltTextContent {
            get {
                return ResourceManager.GetString("emptyAltTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty alternative text.
        /// </summary>
        internal static string emptyAltTextTitle {
            get {
                return ResourceManager.GetString("emptyAltTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is empty..
        /// </summary>
        internal static string emptyTitleContent {
            get {
                return ResourceManager.GetString("emptyTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty title.
        /// </summary>
        internal static string emptyTitleTitle {
            get {
                return ResourceManager.GetString("emptyTitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula with same title already exists in the document. Should the file be overwritten?.
        /// </summary>
        internal static string formulaOverwriteContent {
            get {
                return ResourceManager.GetString("formulaOverwriteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite file.
        /// </summary>
        internal static string formulaOverwriteTitle {
            get {
                return ResourceManager.GetString("formulaOverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image with same name already exists in the document. Should the file be overwritten?.
        /// </summary>
        internal static string imageOverwriteContent {
            get {
                return ResourceManager.GetString("imageOverwriteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite file.
        /// </summary>
        internal static string imageOverwriteTitle {
            get {
                return ResourceManager.GetString("imageOverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image doesn&apos;t exist..
        /// </summary>
        internal static string imagePathContent {
            get {
                return ResourceManager.GetString("imagePathContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image doesn&apos;t exist.
        /// </summary>
        internal static string imagePathTitle {
            get {
                return ResourceManager.GetString("imagePathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible EPUB cannot open this file.
        /// </summary>
        internal static string invalidFileContent {
            get {
                return ResourceManager.GetString("invalidFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        internal static string invalidFileTitle {
            get {
                return ResourceManager.GetString("invalidFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered formula is invalid..
        /// </summary>
        internal static string invalidFormulaContent {
            get {
                return ResourceManager.GetString("invalidFormulaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid formula.
        /// </summary>
        internal static string invalidFormulaTitle {
            get {
                return ResourceManager.GetString("invalidFormulaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid height entry..
        /// </summary>
        internal static string invalidHeightContent {
            get {
                return ResourceManager.GetString("invalidHeightContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid height.
        /// </summary>
        internal static string invalidHeightTitle {
            get {
                return ResourceManager.GetString("invalidHeightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid width entry..
        /// </summary>
        internal static string invalidWidthContent {
            get {
                return ResourceManager.GetString("invalidWidthContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid width.
        /// </summary>
        internal static string invalidWidthTitle {
            get {
                return ResourceManager.GetString("invalidWidthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is already in CSS format.
        /// </summary>
        internal static string jsToCssContent {
            get {
                return ResourceManager.GetString("jsToCssContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already CSS format.
        /// </summary>
        internal static string jsToCssTitle {
            get {
                return ResourceManager.GetString("jsToCssTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input was entered..
        /// </summary>
        internal static string noFormulaContent {
            get {
                return ResourceManager.GetString("noFormulaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing formula.
        /// </summary>
        internal static string noFormulaTitle {
            get {
                return ResourceManager.GetString("noFormulaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required fields are filled out..
        /// </summary>
        internal static string notAllFieldsContent {
            get {
                return ResourceManager.GetString("notAllFieldsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty fields.
        /// </summary>
        internal static string notAllFieldsTitle {
            get {
                return ResourceManager.GetString("notAllFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete all files in temp folder..
        /// </summary>
        internal static string notDeleteTempContent {
            get {
                return ResourceManager.GetString("notDeleteTempContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete files in temp folder.
        /// </summary>
        internal static string notDeleteTempTitle {
            get {
                return ResourceManager.GetString("notDeleteTempTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name is not an EPUB file.
        /// </summary>
        internal static string notEpubContent {
            get {
                return ResourceManager.GetString("notEpubContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an EPUB file.
        /// </summary>
        internal static string notEpubTitle {
            get {
                return ResourceManager.GetString("notEpubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing the given input:.
        /// </summary>
        internal static string parseInputContent {
            get {
                return ResourceManager.GetString("parseInputContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string parseInputTitle {
            get {
                return ResourceManager.GetString("parseInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem reading Content.xhtml.
        /// </summary>
        internal static string probReadContContent {
            get {
                return ResourceManager.GetString("probReadContContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading Content.xhtml.
        /// </summary>
        internal static string probReadContTitle {
            get {
                return ResourceManager.GetString("probReadContTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem reading nav.xhtml.
        /// </summary>
        internal static string probReadNavContent {
            get {
                return ResourceManager.GetString("probReadNavContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading nav.xhtml.
        /// </summary>
        internal static string probReadNavTitle {
            get {
                return ResourceManager.GetString("probReadNavTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the file before exiting?.
        /// </summary>
        internal static string saveLeavingContent {
            get {
                return ResourceManager.GetString("saveLeavingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save change.
        /// </summary>
        internal static string saveLeavingTitle {
            get {
                return ResourceManager.GetString("saveLeavingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder in use. Please leave and then press OK..
        /// </summary>
        internal static string tempInUseContent {
            get {
                return ResourceManager.GetString("tempInUseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp folder is still in use. After pressing OK, the file opening process will stop..
        /// </summary>
        internal static string tempInUseLongContent {
            get {
                return ResourceManager.GetString("tempInUseLongContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder still in use.
        /// </summary>
        internal static string tempInUseLongTitle {
            get {
                return ResourceManager.GetString("tempInUseLongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder in use.
        /// </summary>
        internal static string tempInUseTitle {
            get {
                return ResourceManager.GetString("tempInUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Contents can only be generated if file was created in Accessible EPUB..
        /// </summary>
        internal static string tocAccEpubContent {
            get {
                return ResourceManager.GetString("tocAccEpubContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of contents error.
        /// </summary>
        internal static string tocAccEpubTitle {
            get {
                return ResourceManager.GetString("tocAccEpubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of contents only supported in JavaScript Mode..
        /// </summary>
        internal static string tocJsContent {
            get {
                return ResourceManager.GetString("tocJsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of contents error.
        /// </summary>
        internal static string tocJsTitle {
            get {
                return ResourceManager.GetString("tocJsTitle", resourceCulture);
            }
        }
    }
}
